#!/usr/bin/env perl

use strict;
use warnings;
use lib 'local/lib/perl5';
use Proclet;

my $proclet = Proclet->new( color => 1 );
$proclet->service(
    code => sub {
        exec('carton exec -- plackup -s Starlet --max-worker=4 -R lib script/app.psgi')
    },
    tag  => 'server',
);

$proclet->service(
    code => sub {
        exec('gulp')
    },
    tag  => 'gulp',
);

$proclet->run;
